//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tabler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all changes?.
        /// </summary>
        internal static string GridUI_Discard_all_changes {
            get {
                return ResourceManager.GetString("GridUI_Discard_all_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Key found.
        ///Name: &apos;{0}&apos;
        ///File: &apos;{1}&apos;
        ///Entry: &apos;{2}&apos;.
        /// </summary>
        internal static string GridUI_Duplicate_key_found {
            get {
                return ResourceManager.GetString("GridUI_Duplicate_key_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Key Error.
        /// </summary>
        internal static string GridUI_Duplicate_key_found_title {
            get {
                return ResourceManager.GetString("GridUI_Duplicate_key_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string GridUI_Exit {
            get {
                return ResourceManager.GetString("GridUI_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic XML Exception.
        ///Name: &apos;{0}&apos;
        ///File: &apos;{1}&apos;
        ///Entry: &apos;{2}&apos;.
        /// </summary>
        internal static string GridUI_Generic_xml_exception {
            get {
                return ResourceManager.GetString("GridUI_Generic_xml_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Exception.
        /// </summary>
        internal static string GridUI_Generic_xml_exception_title {
            get {
                return ResourceManager.GetString("GridUI_Generic_xml_exception_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;stringtable.xml&apos; files found..
        /// </summary>
        internal static string GridUI_No_stringtable_xml_files_found {
            get {
                return ResourceManager.GetString("GridUI_No_stringtable_xml_files_found", resourceCulture);
            }
        }
    }
}
