//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tabler.wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tabler.wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version is up to date.
        /// </summary>
        public static string GridUI_CheckForNewVersion_Current_version_is_up_to_date {
            get {
                return ResourceManager.GetString("GridUI_CheckForNewVersion_Current_version_is_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the new version at.
        /// </summary>
        public static string GridUI_CheckForNewVersion_Download_the_new_version_at {
            get {
                return ResourceManager.GetString("GridUI_CheckForNewVersion_Download_the_new_version_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string GridUI_CheckForNewVersion_New_version_available {
            get {
                return ResourceManager.GetString("GridUI_CheckForNewVersion_New_version_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all changes?.
        /// </summary>
        public static string GridUI_Discard_all_changes {
            get {
                return ResourceManager.GetString("GridUI_Discard_all_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Key(s) found.
        ///Name: &apos;{0}&apos;
        ///File: &apos;{1}&apos;
        ///Entry: &apos;{2}&apos;.
        /// </summary>
        public static string GridUI_Duplicate_key_found {
            get {
                return ResourceManager.GetString("GridUI_Duplicate_key_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Key Error.
        /// </summary>
        public static string GridUI_Duplicate_key_found_title {
            get {
                return ResourceManager.GetString("GridUI_Duplicate_key_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        public static string GridUI_Exit {
            get {
                return ResourceManager.GetString("GridUI_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic XML Exception.
        ///Name: &apos;{0}&apos;
        ///File: &apos;{1}&apos;
        ///Entry: &apos;{2}&apos;.
        /// </summary>
        public static string GridUI_Generic_xml_exception {
            get {
                return ResourceManager.GetString("GridUI_Generic_xml_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Exception.
        /// </summary>
        public static string GridUI_Generic_xml_exception_title {
            get {
                return ResourceManager.GetString("GridUI_Generic_xml_exception_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed Stringtable Encountered.
        ///File: &apos;{0}&apos;
        ///Message: &apos;{1}&apos;
        ///
        ///More information: https://community.bistudio.com/wiki/Stringtable.xml.
        /// </summary>
        public static string GridUI_Malformed_Stringtable_exception {
            get {
                return ResourceManager.GetString("GridUI_Malformed_Stringtable_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed Stringtable.
        /// </summary>
        public static string GridUI_Malformed_Stringtable_exception_title {
            get {
                return ResourceManager.GetString("GridUI_Malformed_Stringtable_exception_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;stringtable.xml&apos; files found..
        /// </summary>
        public static string GridUI_No_stringtable_xml_files_found {
            get {
                return ResourceManager.GetString("GridUI_No_stringtable_xml_files_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open?.
        /// </summary>
        public static string GridUI_Open {
            get {
                return ResourceManager.GetString("GridUI_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved..
        /// </summary>
        public static string GridUI_saveToolStripMenuItem_Click_Successfully_saved {
            get {
                return ResourceManager.GetString("GridUI_saveToolStripMenuItem_Click_Successfully_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default hello world.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open language file(s).
        /// </summary>
        public static string MainUI_OpenFile {
            get {
                return ResourceManager.GetString("MainUI_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save language file(s).
        /// </summary>
        public static string MainUI_SaveFile {
            get {
                return ResourceManager.GetString("MainUI_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string TranslationProgress_AxisX_Title {
            get {
                return ResourceManager.GetString("TranslationProgress_AxisX_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Missing Translations.
        /// </summary>
        public static string TranslationProgress_AxisY_Title {
            get {
                return ResourceManager.GetString("TranslationProgress_AxisY_Title", resourceCulture);
            }
        }
    }
}
